/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bccbb9",
        "surface-container-high": "#e7e8e9",
        "on-surface": "#191c1d",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-container": "#004b1e",
        "tertiary": "#006d30",
        "on-primary-fixed-variant": "#005321",
        "surface-bright": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#4ae176",
        "primary-fixed": "#6bff8f",
        "on-secondary-fixed-variant": "#474646",
        "surface-tint": "#006e2f",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "primary-container": "#22c55e",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed-variant": "#005323",
        "outline": "#6d7b6c",
        "secondary-fixed": "#e5e2e1",
        "error-container": "#ffdad6",
        "surface": "#f8f9fa",
        "primary": "#006e2f",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed": "#002109",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "on-surface-variant": "#3d4a3d",
        "on-tertiary-container": "#004a1f",
        "tertiary-container": "#5ebf74",
        "secondary": "#5f5e5e",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed": "#00210a",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1d",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-container": "#e5e2e1",
        "primary-fixed-dim": "#4ae176",
        "tertiary-fixed": "#95f8a7",
        "tertiary-fixed-dim": "#79db8d",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-container": "#656464",
        "background": "#f8f9fa",
        // Legacy colors to prevent breakages if any components reference them
        accent: "#22c55e",
        destructive: "#ba1a1a",
        muted: "#6b7280",
        border: "#bccbb9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "12px",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "2xl": "48px",
        "base": "8px",
        "margin-desktop": "32px",
        "gutter": "16px",
        "sm": "8px",
        "xs": "4px",
        "lg": "24px",
        "xl": "32px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "sans-serif"],
        "button": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "button": ["15px", {"lineHeight": "20px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
